SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM REST_INFO AS r INNER JOIN (SELECT FOOD_TYPE, max(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) AS s ON r.FOOD_TYPE = s.FOOD_TYPE
WHERE r.FAVORITES = s.FAVORITES
ORDER BY r.FOOD_TYPE DESC;